# Generated by Django 6.0.5 on 2026-05-25 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel'), ('sap_procurement', 'SAP Procurement'), ('utility_electricity', 'Utility Electricity'), ('travel_flight', 'Travel Flight'), ('travel_hotel', 'Travel Hotel'), ('travel_ground', 'Travel Ground')], max_length=30)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 (Direct)'), ('2', 'Scope 2 (Electricity)'), ('3', 'Scope 3 (Value Chain)')], max_length=1)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('analyst_notes', models.TextField(blank=True)),
                ('edit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionbatch')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.tenant')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='review.normalizedrecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('missing_required_field', 'Missing Required Field'), ('future_date', 'Future Date'), ('negative_quantity', 'Negative Quantity'), ('outlier_high', 'Unusually High Value'), ('duplicate_record', 'Possible Duplicate'), ('utility_long_billing_period', 'Long Billing Period'), ('travel_missing_distance', 'Missing Distance'), ('unit_conversion_assumption', 'Unit Conversion Assumed'), ('zero_quantity', 'Zero Quantity')], max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warn', 'Warning'), ('info', 'Info')], max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='review.normalizedrecord')),
            ],
        ),
    ]
